![images.png]()


**LIBRERIAS**

CURSO DE PYTHON

DIRECCION DE EDUCACIÓN CONTINUA

FUNDACION UNIVERSITARIA CAFAM

DOCENTE: NICOLAS MOJICA GOMEZ

ESTUDIANTE: **LUIS GONZALO NAVARRO P.**


---

In [21]:
import pandas as pd

ejecuciones = pd.read_excel("/content/sample_data/Base ejecuciones Oct-17.xlsx")

In [42]:
planta = pd.read_excel("//content/sample_data/Planta.xlsx")
horas = pd.read_excel("/content/sample_data/Punto # 3.xlsx")
prestamo = pd.read_excel("/content/sample_data/Punto # 4.xlsx")

/usr/local/lib/python3.10/dist-packages/openpyxl/worksheet/header_footer.py:48: UserWarning: Cannot parse header or footer so it will be ignored
  warn("""Cannot parse header or footer so it will be ignored""")
/usr/local/lib/python3.10/dist-packages/openpyxl/worksheet/header_footer.py:48: UserWarning: Cannot parse header or footer so it will be ignored
  warn("""Cannot parse header or footer so it will be ignored""")
/usr/local/lib/python3.10/dist-packages/openpyxl/worksheet/header_footer.py:48: UserWarning: Cannot parse header or footer so it will be ignored
  warn("""Cannot parse header or footer so it will be ignored""")

In [24]:
ejecuciones

,CEDULA,N° Cuentas,N° CDT,N° Tarjetas De Crédito,N° Debitos Automáticos,Plan Familia (Millones),Consumo (Millones),Libranza (Millones),Compra Cartera (Millones),Vehículo (Millones),N° Seguros Desempleo,N° Seguros Fraude,N° Seguros Accidentes Per.
0,9.375240e+06,64,2,12,1,6.150000e+06,8.500000e+07,2.000000e+07,31588778,0.0,0,4,9
1,1.023008e+09,93,6,16,10,9.930000e+06,9.197159e+07,0.000000e+00,75555084,0.0,6,16,5
2,4.196091e+07,61,3,10,0,8.055000e+06,8.020000e+07,1.450000e+07,81043832,0.0,9,9,10
3,1.010229e+09,63,2,14,4,7.995000e+06,1.038516e+08,1.000000e+08,123733612,0.0,4,5,0
4,1.054920e+09,80,3,15,5,7.970833e+06,7.500000e+07,3.600000e+07,69315000,0.0,5,10,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...
491,8.080704e+07,85,9,12,2,5.643125e+06,8.380000e+07,0.000000e+00,83085000,0.0,0,10,2
492,8.005812e+07,74,1,8,6,1.785000e+06,5.050000e+07,1.470000e+07,59417965,0.0,1,3,2
493,5.206726e+07,78,6,12,4,1.102967e+07,9.760000e+07,0.000000e+00,139130000,0.0,4,9,10
494,1.088009e+09,99,6,19,4,9.349646e+06,7.930000e+07,1.700000e+07,58564000,0.0,11,16,16
495,NaN,30842,1503,4249,1405,2.385297e+09,3.242029e+10,6.883377e+09,28889158084,559389000.0,1489,3458,2907

In [34]:
planta

,CEDULA,COD OFICINA,CODIGO GESTOR,OFICINA,NOMBRE,JORNADA,ZONA,N° Cuentas,N° CDT,N° Tarjetas De Crédito,N° Debitos Automáticos,Plan Familia (Millones),Consumo (Millones),Libranza (Millones),Compra Cartera (Millones),Vehículo (Millones),N° Seguros Desempleo,N° Seguros Fraude,N° Seguros Accidentes Per.
0,9375240,12,9658,BOGOTÁ CHAPINERO,LUIS JAVIER FUENTES LEON,NORMAL,9002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1023008416,73,9877,BOGOTÁ RESTREPO,RUBEN DARIO JIMENEZ PRECIADO,NORMAL,9004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,41960913,228,31597,ARMENIA CENTRO,JESSICA ALEXANDRA GIL BERRIO,NORMAL,9005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1010229345,280,36873,BOGOTÁ LOS HAYUELOS,DAVID FELIPE VANEGAS DEL CASTILLO,NORMAL,9003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1054920307,203,9817,PEREIRA DOSQUEBRADAS,LAURA LEDESMA TREJOS,NORMAL,9005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
476,1019088583,51,38234,BOGOTÁ GALERIAS,JENNY ALEXANDRA CASAS MONROY,NORMAL,9002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
477,80807040,634,9196,BOGOTÁ SUBA IMPERIAL,ALBERTO GUTIERREZ G,NORMAL,9001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
478,80058124,757,9863,MOSQUERA,CAMILO ANDRES CASTRILLON MURILLO,NORMAL,9003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
479,52067261,37,9905,BOGOTÁ UNICENTRO,ADRIANA CARDENAS REYES,NORMAL,9001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
480,1088008856,206,37379,PEREIRA CRA. SEPTIMA,EVA MARIA MUÐOZ ARABIA,NORMAL,9005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [35]:
UnionEjecucionesPlanta = pd.merge(planta,ejecuciones,on="CEDULA",how="inner")

In [36]:
UnionEjecucionesPlanta

,CEDULA,COD OFICINA,CODIGO GESTOR,OFICINA,NOMBRE,JORNADA,ZONA,N° Cuentas_x,N° CDT_x,N° Tarjetas De Crédito_x,...,N° Tarjetas De Crédito_y,N° Debitos Automáticos_y,Plan Familia (Millones)_y,Consumo (Millones)_y,Libranza (Millones)_y,Compra Cartera (Millones)_y,Vehículo (Millones)_y,N° Seguros Desempleo_y,N° Seguros Fraude_y,N° Seguros Accidentes Per._y
0,9375240,12,9658,BOGOTÁ CHAPINERO,LUIS JAVIER FUENTES LEON,NORMAL,9002,NaN,NaN,NaN,...,12,1,6.150000e+06,8.500000e+07,20000000.0,31588778,0.0,0,4,9
1,1023008416,73,9877,BOGOTÁ RESTREPO,RUBEN DARIO JIMENEZ PRECIADO,NORMAL,9004,NaN,NaN,NaN,...,16,10,9.930000e+06,9.197159e+07,0.0,75555084,0.0,6,16,5
2,41960913,228,31597,ARMENIA CENTRO,JESSICA ALEXANDRA GIL BERRIO,NORMAL,9005,NaN,NaN,NaN,...,10,0,8.055000e+06,8.020000e+07,14500000.0,81043832,0.0,9,9,10
3,1010229345,280,36873,BOGOTÁ LOS HAYUELOS,DAVID FELIPE VANEGAS DEL CASTILLO,NORMAL,9003,NaN,NaN,NaN,...,14,4,7.995000e+06,1.038516e+08,100000000.0,123733612,0.0,4,5,0
4,1054920307,203,9817,PEREIRA DOSQUEBRADAS,LAURA LEDESMA TREJOS,NORMAL,9005,NaN,NaN,NaN,...,15,5,7.970833e+06,7.500000e+07,36000000.0,69315000,0.0,5,10,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
476,1019088583,51,38234,BOGOTÁ GALERIAS,JENNY ALEXANDRA CASAS MONROY,NORMAL,9002,NaN,NaN,NaN,...,2,2,0.000000e+00,1.810000e+07,36000000.0,47253587,0.0,0,1,7
477,80807040,634,9196,BOGOTÁ SUBA IMPERIAL,ALBERTO GUTIERREZ G,NORMAL,9001,NaN,NaN,NaN,...,12,2,5.643125e+06,8.380000e+07,0.0,83085000,0.0,0,10,2
478,80058124,757,9863,MOSQUERA,CAMILO ANDRES CASTRILLON MURILLO,NORMAL,9003,NaN,NaN,NaN,...,8,6,1.785000e+06,5.050000e+07,14700000.0,59417965,0.0,1,3,2
479,52067261,37,9905,BOGOTÁ UNICENTRO,ADRIANA CARDENAS REYES,NORMAL,9001,NaN,NaN,NaN,...,12,4,1.102967e+07,9.760000e+07,0.0,139130000,0.0,4,9,10
480,1088008856,206,37379,PEREIRA CRA. SEPTIMA,EVA MARIA MUÐOZ ARABIA,NORMAL,9005,NaN,NaN,NaN,...,19,4,9.349646e+06,7.930000e+07,17000000.0,58564000,0.0,11,16,16

In [39]:
horas

               Nombre  Horas Extras  Valor a Pagar  Participación
0          Aura Mejia          52.0            NaN            NaN
1   Catalina Candamil          88.0            NaN            NaN
2     Diego Sarmiento          88.0            NaN            NaN
3     Hector Mosquera          56.0            NaN            NaN
4       Jalima Shaker          13.0            NaN            NaN
5        Javier Jerez          37.0            NaN            NaN
6         José Campos          25.0            NaN            NaN
7     Lianer Barragan          69.0            NaN            NaN
8     Marcela Caicedo          86.0            NaN            NaN
9       Myriam Farfan          63.0            NaN            NaN
10     Nayibe Peralta          22.0            NaN            NaN
11     Patricia López          17.0            NaN            NaN
12     Rafael Montoya          18.0            NaN            NaN
13      Romulo Talero          22.0            NaN            NaN
14      Uriel Sánchez          21.0            NaN            NaN
15                NaN           NaN            NaN            NaN
16            Totales           NaN            NaN            NaN

In [40]:
horas["TotalPagar"]= horas["Horas Extras"]*5000

In [41]:
horas

               Nombre  Horas Extras  Valor a Pagar  Participación  TotalPagar
0          Aura Mejia          52.0            NaN            NaN    260000.0
1   Catalina Candamil          88.0            NaN            NaN    440000.0
2     Diego Sarmiento          88.0            NaN            NaN    440000.0
3     Hector Mosquera          56.0            NaN            NaN    280000.0
4       Jalima Shaker          13.0            NaN            NaN     65000.0
5        Javier Jerez          37.0            NaN            NaN    185000.0
6         José Campos          25.0            NaN            NaN    125000.0
7     Lianer Barragan          69.0            NaN            NaN    345000.0
8     Marcela Caicedo          86.0            NaN            NaN    430000.0
9       Myriam Farfan          63.0            NaN            NaN    315000.0
10     Nayibe Peralta          22.0            NaN            NaN    110000.0
11     Patricia López          17.0            NaN            NaN     85000.0
12     Rafael Montoya          18.0            NaN            NaN     90000.0
13      Romulo Talero          22.0            NaN            NaN    110000.0
14      Uriel Sánchez          21.0            NaN            NaN    105000.0
15                NaN           NaN            NaN            NaN         NaN
16            Totales           NaN            NaN            NaN         NaN

In [43]:
prestamo

      NOMBRE  EDAD ESTADO CIVIL  PRESTAMO
0     Marcos    35      SOLTERO       NaN
1     Felipe    40   DIVORCIADO       NaN
2     Sandra    28      SOLTERO       NaN
3    Marcela    36      SOLTERO       NaN
4      Ramón    23   DIVORCIADO       NaN
5       Juan    51      SOLTERO       NaN
6    Enrique    34      SOLTERO       NaN
7   Fernando    48   DIVORCIADO       NaN
8    Natalia    26      SOLTERO       NaN
9     Ximena    22   DIVORCIADO       NaN
10  Carolina    36      SOLTERO       NaN

In [45]:
import numpy as np



prestamo
prestamo["Resultado"] = np.where((prestamo["EDAD"]>=29) & (prestamo["ESTADO CIVIL"]=="SOLTERO"),"Aprobado","Negado")

In [46]:
prestamo

      NOMBRE  EDAD ESTADO CIVIL  PRESTAMO Resultado
0     Marcos    35      SOLTERO       NaN  Aprobado
1     Felipe    40   DIVORCIADO       NaN    Negado
2     Sandra    28      SOLTERO       NaN    Negado
3    Marcela    36      SOLTERO       NaN  Aprobado
4      Ramón    23   DIVORCIADO       NaN    Negado
5       Juan    51      SOLTERO       NaN  Aprobado
6    Enrique    34      SOLTERO       NaN  Aprobado
7   Fernando    48   DIVORCIADO       NaN    Negado
8    Natalia    26      SOLTERO       NaN    Negado
9     Ximena    22   DIVORCIADO       NaN    Negado
10  Carolina    36      SOLTERO       NaN  Aprobado